[package]
name = "burn_import_testbed"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
burn-import = { git = "https://github.com/tracel-ai/burn", branch = "main" }

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn", branch = "main", features = [
  "wgpu",
] }
burn-import = { git = "https://github.com/tracel-ai/burn", branch = "main" }
