[package]
name = "burn_import_testbed"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
burn-import = { git = "https://github.com/tracel-ai/burn", branch = "main" }
# burn-import = { git = "https://github.com/tracel-ai/burn", rev = "4a3fc9d4a094bc7ce4205fbc83b61da383308a43" }

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn", branch = "main", features = [
  "wgpu",
] }
burn-import = { git = "https://github.com/tracel-ai/burn", branch = "main" }
# burn = { git = "https://github.com/tracel-ai/burn", rev = "4a3fc9d4a094bc7ce4205fbc83b61da383308a43", features = [
#   "wgpu",
# ] }
# burn-import = { git = "https://github.com/tracel-ai/burn", rev = "4a3fc9d4a094bc7ce4205fbc83b61da383308a43" }
# burn-wgpu = { git = "https://github.com/tracel-ai/burn", rev = "4a3fc9d4a094bc7ce4205fbc83b61da383308a43" }
