[package]
name = "burn_import_testbed"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
burn-import = { git = "https://github.com/tracel-ai/burn", rev = "be5eb910d4e8f91a7162c523a2d390d01a41a12d" }

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn", rev = "be5eb910d4e8f91a7162c523a2d390d01a41a12d", features = [
  "wgpu",
  "ndarray",
] }
