[package]
name = "burn_import_testbed"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"

[build-dependencies]
burn-import = { git = "https://github.com/tracel-ai/burn", rev = "be705466c9a45e0dd7f93c04761e844c7ff644c1" }

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn", rev = "be705466c9a45e0dd7f93c04761e844c7ff644c1", features = [
  "wgpu",
  "ndarray",
] }
